// Asia content: names, capitals, funny memory cues (Indian English + light Hinglish),
// level grouping, colours, guess-game hints and visual anchors.
// Same audio file naming as Europe: {cc}_name, {cc}_cue, {cc}_capital, {cc}_findcap,
// {cc}_hint, {cc}_tease, {cc}_captease, {cc}_flaghint, {cc}_capcue.

export const COUNTRIES = {
  // ---- Level 1: Apna Ghar — India & Neighbours ----
  in: {
    name: 'India', capital: 'New Delhi', color: '#ff9933',
    cue: "India! Apna ghar — our home! The Taj Mahal, dancing peacocks, and tigers in the jungle! Jai Hind!",
    findcap: "New Delhi! Where does New Delhi live? Find New Delhi's country!",
  },
  pk: {
    name: 'Pakistan', capital: 'Islamabad', color: '#66bb6a',
    cue: "Pakistan! Our neighbour! Everyone plays cricket — howzat! And K2, a giant giant mountain!",
    findcap: "Islamabad! Where does Islamabad live? Find Islamabad's country!",
  },
  np: {
    name: 'Nepal', capital: 'Kathmandu', color: '#ef5350',
    cue: "Nepal! Mount Everest lives here — the TALLEST mountain in the whole wide world! So so tall!",
    findcap: "Kathmandu! Where does Kathmandu live? Find Kathmandu's country!",
  },
  bt: {
    name: 'Bhutan', capital: 'Thimphu', color: '#ffb74d',
    cue: "Bhutan! The land of the thunder dragon! Grrr-boom! And everyone there measures happiness!",
    findcap: "Thimphu! Where does Thimphu live? Find Thimphu's country!",
  },
  bd: {
    name: 'Bangladesh', capital: 'Dhaka', color: '#26a69a',
    cue: "Bangladesh! Rivers rivers everywhere, and the royal Bengal tiger says halum!",
    findcap: "Dhaka! Where does Dhaka live? Find Dhaka's country!",
  },
  lk: {
    name: 'Sri Lanka', capital: 'Colombo', color: '#ba68c8',
    cue: "Sri Lanka! A little teardrop island! Elephants walk on beaches and coconuts fall — dhap!",
    findcap: "Colombo! Where does Colombo live? Find Colombo's country!",
  },

  // ---- Level 2: The Far East ----
  cn: {
    name: 'China', capital: 'Beijing', color: '#e57373',
    cue: "China! The Great Wall — a wall SO long it goes on and on and on! And cute pandas munching bamboo!",
    findcap: "Beijing! Where does Beijing live? Find Beijing's country!",
  },
  jp: {
    name: 'Japan', capital: 'Tokyo', color: '#f06292',
    cue: "Japan! Pink cherry blossoms, bullet trains going zoooom, and sushi! Konnichiwa!",
    findcap: "Tokyo! Where does Tokyo live? Find Tokyo's country!",
  },
  kr: {
    name: 'South Korea', capital: 'Seoul', color: '#5c9ce6',
    cue: "South Korea! K-pop music — everybody dance! And spicy yummy kimchi!",
    findcap: "Seoul! Where does Seoul live? Find Seoul's country!",
  },
  kp: {
    name: 'North Korea', capital: 'Pyongyang', color: '#90a4ae',
    cue: "North Korea! A very very quiet country up north — shhh!",
    findcap: "Pyongyang! Where does Pyongyang live? Find Pyongyang's country!",
  },
  mn: {
    name: 'Mongolia', capital: 'Ulaanbaatar', color: '#8d6e63',
    cue: "Mongolia! Horses run free on grass that never ever ends! And people live in round tent houses!",
    findcap: "Ulaanbaatar! Where does Ulaanbaatar live? Find Ulaanbaatar's country!",
  },
  tw: {
    name: 'Taiwan', capital: 'Taipei', color: '#4db6ac',
    cue: "Taiwan! Bubble tea comes from here — slurp slurp, boba balls!",
    findcap: "Taipei! Where does Taipei live? Find Taipei's country!",
  },

  // ---- Level 3: Jungle Friends ----
  mm: {
    name: 'Myanmar', capital: 'Naypyidaw', color: '#ffca28',
    cue: "Myanmar! Golden pagodas shine everywhere — so much gold, twinkle twinkle!",
    findcap: "Naypyidaw! Where does Naypyidaw live? Find Naypyidaw's country!",
  },
  th: {
    name: 'Thailand', capital: 'Bangkok', color: '#7e57c2',
    cue: "Thailand! Elephants say hello with their trunks, and yummy noodles called pad thai!",
    findcap: "Bangkok! Where does Bangkok live? Find Bangkok's country!",
  },
  la: {
    name: 'Laos', capital: 'Vientiane', color: '#81c784',
    cue: "Laos! Sticky rice in little baskets, and slow slow boats on a big river!",
    findcap: "Vientiane! Where does Vientiane live? Find Vientiane's country!",
  },
  kh: {
    name: 'Cambodia', capital: 'Phnom Penh', color: '#4dd0e1',
    cue: "Cambodia! Angkor Wat — the biggest temple in the whole world, hiding in the jungle!",
    findcap: "Phnom Penh! Where does Phnom Penh live? Find Phnom Penh's country!",
  },
  vn: {
    name: 'Vietnam', capital: 'Hanoi', color: '#ff7043',
    cue: "Vietnam! Pho noodle soup — slurp! And boats sail in a bay full of stone mountains!",
    findcap: "Hanoi! Where does Hanoi live? Find Hanoi's country!",
  },

  // ---- Level 4: Island Hoppers ----
  my: {
    name: 'Malaysia', capital: 'Kuala Lumpur', color: '#42a5f5',
    cue: "Malaysia! Twin towers — two tall silver towers holding hands with a bridge!",
    findcap: "Kuala Lumpur! Where does Kuala Lumpur live? Find Kuala Lumpur's country!",
  },
  sg: {
    name: 'Singapore', capital: 'Singapore City', color: '#ec407a',
    cue: "Singapore! The Merlion — a lion with a fish tail spitting water! Whoosh!",
    findcap: "Singapore City! Where does Singapore City live? Find its country!",
  },
  id: {
    name: 'Indonesia', capital: 'Jakarta', color: '#9ccc65',
    cue: "Indonesia! Seventeen THOUSAND islands! And real dragons live on one — Komodo dragons!",
    findcap: "Jakarta! Where does Jakarta live? Find Jakarta's country!",
  },
  ph: {
    name: 'Philippines', capital: 'Manila', color: '#29b6f6',
    cue: "Philippines! Thousands of islands, the sweetest mangoes, and jeepney buses — beep beep!",
    findcap: "Manila! Where does Manila live? Find Manila's country!",
  },
  bn: {
    name: 'Brunei', capital: 'Bandar Seri Begawan', color: '#fdd835',
    cue: "Brunei! A tiny country where the king lives in the biggest palace in the world!",
    findcap: "Bandar Seri Begawan! Where does it live? Find its country!",
  },

  // ---- Level 5: Silk Road Riders ----
  kz: {
    name: 'Kazakhstan', capital: 'Astana', color: '#26c6da',
    cue: "Kazakhstan! So so big! Apples were born here — the very first apples! And horses everywhere!",
    findcap: "Astana! Where does Astana live? Find Astana's country!",
  },
  uz: {
    name: 'Uzbekistan', capital: 'Tashkent', color: '#66bb6a',
    cue: "Uzbekistan! Blue blue tiled palaces on the old Silk Road, and sweet sweet melons!",
    findcap: "Tashkent! Where does Tashkent live? Find Tashkent's country!",
  },
  tm: {
    name: 'Turkmenistan', capital: 'Ashgabat', color: '#ab47bc',
    cue: "Turkmenistan! A desert with a big fire pit that never stops burning — whoa, so hot!",
    findcap: "Ashgabat! Where does Ashgabat live? Find Ashgabat's country!",
  },
  kg: {
    name: 'Kyrgyzstan', capital: 'Bishkek', color: '#ffa726',
    cue: "Kyrgyzstan! Mountains everywhere, and golden eagles that fly with their friends the hunters!",
    findcap: "Bishkek! Where does Bishkek live? Find Bishkek's country!",
  },
  tj: {
    name: 'Tajikistan', capital: 'Dushanbe', color: '#ef9a4d',
    cue: "Tajikistan! Mountains SO high, people call them the Roof of the World!",
    findcap: "Dushanbe! Where does Dushanbe live? Find Dushanbe's country!",
  },
  af: {
    name: 'Afghanistan', capital: 'Kabul', color: '#a1887f',
    cue: "Afghanistan! Sweet melons and juicy anaar grow between big dry mountains!",
    findcap: "Kabul! Where does Kabul live? Find Kabul's country!",
  },

  // ---- Level 6: Desert Kingdoms ----
  sa: {
    name: 'Saudi Arabia', capital: 'Riyadh', color: '#9575cd',
    cue: "Saudi Arabia! A giant sandy desert with camels — and khajoor dates, so sweet!",
    findcap: "Riyadh! Where does Riyadh live? Find Riyadh's country!",
  },
  ae: {
    name: 'The Emirates', capital: 'Abu Dhabi', color: '#ffb300',
    cue: "The Emirates! The tallest building in the WHOLE world is here — up up up it goes!",
    findcap: "Abu Dhabi! Where does Abu Dhabi live? Find Abu Dhabi's country!",
  },
  qa: {
    name: 'Qatar', capital: 'Doha', color: '#7986cb',
    cue: "Qatar! The football World Cup was played here — right in the desert! Goal!",
    findcap: "Doha! Where does Doha live? Find Doha's country!",
  },
  om: {
    name: 'Oman', capital: 'Muscat', color: '#4fc3f7',
    cue: "Oman! Magic-lamp land! Nice-smelling frankincense, and dolphins jumping in the sea!",
    findcap: "Muscat! Where does Muscat live? Find Muscat's country!",
  },
  ye: {
    name: 'Yemen', capital: 'Sanaa', color: '#d4e157',
    cue: "Yemen! Gingerbread houses! Tall old brown houses with white icing patterns!",
    findcap: "Sanaa! Where does Sanaa live? Find Sanaa's country!",
  },
  kw: {
    name: 'Kuwait', capital: 'Kuwait City', color: '#80cbc4',
    cue: "Kuwait! Tall towers holding big blue balls, right by the sea!",
    findcap: "Kuwait City! Where does Kuwait City live? Find its country!",
  },

  // ---- Level 7: Old Old Lands ----
  ir: {
    name: 'Iran', capital: 'Tehran', color: '#aed581',
    cue: "Iran! Fluffy Persian cats — meow! And carpets so pretty they look like flower gardens!",
    findcap: "Tehran! Where does Tehran live? Find Tehran's country!",
  },
  iq: {
    name: 'Iraq', capital: 'Baghdad', color: '#ce93d8',
    cue: "Iraq! The very first writing in the world was invented here — on clay! And tall date palms!",
    findcap: "Baghdad! Where does Baghdad live? Find Baghdad's country!",
  },
  tr: {
    name: 'Turkey', capital: 'Ankara', color: '#f48fb1',
    cue: "Turkey! Like the bird — gobble gobble! Hot air balloons float over magic fairy chimneys!",
    findcap: "Ankara! Where does Ankara live? Find Ankara's country!",
  },
  sy: {
    name: 'Syria', capital: 'Damascus', color: '#dce775',
    cue: "Syria! One of the oldest oldest cities in the whole world lives here!",
    findcap: "Damascus! Where does Damascus live? Find Damascus's country!",
  },
  jo: {
    name: 'Jordan', capital: 'Amman', color: '#ff8a65',
    cue: "Jordan! A whole city carved into pink rock — Petra! And a sea where you float like a boat!",
    findcap: "Amman! Where does Amman live? Find Amman's country!",
  },
  il: {
    name: 'Israel', capital: 'Jerusalem', color: '#64b5f6',
    cue: "Israel! A sea SO salty that you float on top like a rubber duck!",
    findcap: "Jerusalem! Where does Jerusalem live? Find Jerusalem's country!",
  },
  lb: {
    name: 'Lebanon', capital: 'Beirut', color: '#81c784',
    cue: "Lebanon! Big old cedar trees — so special, one is on the flag!",
    findcap: "Beirut! Where does Beirut live? Find Beirut's country!",
  },

  // ---- Level 8: Mountain Buddies ----
  ge: {
    name: 'Georgia', capital: 'Tbilisi', color: '#ff8a65',
    cue: "Georgia! Big mountains, sweet grapes, and dancing with swords — hop hop hop!",
    findcap: "Tbilisi! Where does Tbilisi live? Find Tbilisi's country!",
  },
  am: {
    name: 'Armenia', capital: 'Yerevan', color: '#ba68c8',
    cue: "Armenia! A big snowy mountain watches over everyone, and apricots grow sweet sweet!",
    findcap: "Yerevan! Where does Yerevan live? Find Yerevan's country!",
  },
  az: {
    name: 'Azerbaijan', capital: 'Baku', color: '#4db6ac',
    cue: "Azerbaijan! The land of fire! Little fires burn right out of the ground — whoosh!",
    findcap: "Baku! Where does Baku live? Find Baku's country!",
  },
};

export const LEVELS = [
  { name: 'Apna Ghar', emoji: '🐯', ccs: ['in', 'pk', 'np', 'bt', 'bd', 'lk'] },
  { name: 'The Far East', emoji: '🐼', ccs: ['cn', 'jp', 'kr', 'kp', 'mn', 'tw'] },
  { name: 'Jungle Friends', emoji: '🐘', ccs: ['mm', 'th', 'la', 'kh', 'vn'] },
  { name: 'Island Hoppers', emoji: '🏝️', ccs: ['my', 'sg', 'id', 'ph', 'bn'] },
  { name: 'Silk Road Riders', emoji: '🐎', ccs: ['kz', 'uz', 'tm', 'kg', 'tj', 'af'] },
  { name: 'Desert Kingdoms', emoji: '🐪', ccs: ['sa', 'ae', 'qa', 'om', 'ye', 'kw'] },
  { name: 'Old Old Lands', emoji: '🏺', ccs: ['ir', 'iq', 'tr', 'sy', 'jo', 'il', 'lb'] },
  { name: 'Mountain Buddies', emoji: '⛰️', ccs: ['ge', 'am', 'az'] },
];

/* Short display names so labels fit inside small countries */
export const SHORT = {
  in: 'India', pk: 'Pakistan', np: 'Nepal', bt: 'Bhutan', bd: 'Bangla.',
  lk: 'Sri Lanka', cn: 'China', jp: 'Japan', kr: 'S.Korea', kp: 'N.Korea',
  mn: 'Mongolia', tw: 'Taiwan', mm: 'Myanmar', th: 'Thailand', la: 'Laos',
  kh: 'Camb.', vn: 'Vietnam', my: 'Malaysia', sg: 'Sing.', id: 'Indonesia',
  ph: 'Philipp.', bn: 'Brunei', kz: 'Kazakh.', uz: 'Uzbek.', tm: 'Turkmen.',
  kg: 'Kyrgyz.', tj: 'Tajik.', af: 'Afghan.', sa: 'Saudi', ae: 'UAE',
  qa: 'Qatar', om: 'Oman', ye: 'Yemen', kw: 'Kuwait', ir: 'Iran', iq: 'Iraq',
  tr: 'Turkey', sy: 'Syria', jo: 'Jordan', il: 'Israel', lb: 'Leban.',
  ge: 'Georgia', am: 'Armenia', az: 'Azerb.',
};

export const GUESS = {
  in: { hint: "I am YOUR home! Apna ghar! The Taj Mahal is here, peacocks dance, and tigers roam my jungles!",
    tease: "My name starts with, In... In...",
    capTease: "My capital city starts with, New Deh... New Deh...",
    flagHint: "Orange, white and green with a blue wheel — apna jhanda!" },
  pk: { hint: "I am right next to your home! Everyone here plays cricket — howzat!",
    tease: "My name starts with, Paki... Paki...",
    capTease: "My capital city starts with, Islama... Islama...",
    flagHint: "Green with a white moon and star!" },
  np: { hint: "The tallest mountain in the whole world stands in me! Up up up!",
    tease: "My name starts with, Neh... Neh...",
    capTease: "My capital city starts with, Kath... Kath...",
    flagHint: "The only flag that is not a rectangle — two red triangles!" },
  bt: { hint: "A thunder dragon lives in my name! Grrr-boom! And I measure happiness!",
    tease: "My name starts with, Bhoo... Bhoo...",
    capTease: "My capital city starts with, Thim... Thim...",
    flagHint: "Orange and yellow with a white dragon!" },
  bd: { hint: "Rivers run everywhere in me, and the royal Bengal tiger says halum!",
    tease: "My name starts with, Bangla... Bangla...",
    capTease: "My capital city starts with, Dha... Dha...",
    flagHint: "Green with a red circle like the sun!" },
  lk: { hint: "I am a little teardrop island under India! Elephants walk on my beaches!",
    tease: "My name starts with, Sree... Sree...",
    capTease: "My capital city starts with, Colom... Colom...",
    flagHint: "A golden lion holding a sword, with orange and green stripes!" },
  cn: { hint: "My wall is SO long you can walk for years! And pandas munch bamboo in me!",
    tease: "My name starts with, Chai... Chai...",
    capTease: "My capital city starts with, Bei... Bei...",
    flagHint: "Red with one big yellow star and four little ones!" },
  jp: { hint: "Pink cherry blossoms fall in me, and my trains zoom like bullets!",
    tease: "My name starts with, Ja... Ja...",
    capTease: "My capital city starts with, Toh... Toh...",
    flagHint: "White with one big red circle — like the sun!" },
  kr: { hint: "K-pop music comes from me — everybody dance! And spicy kimchi!",
    tease: "My name starts with, Koh... Koh...",
    capTease: "My capital city starts with, Soh... Soh...",
    flagHint: "White with a red and blue circle like a yin-yang!" },
  kp: { hint: "I am the very quiet country up north — shhh!",
    tease: "My name starts with, North Koh... North Koh...",
    capTease: "My capital city starts with, Pyong... Pyong...",
    flagHint: "Red and blue stripes with a red star in a white circle!" },
  mn: { hint: "Horses run free in me on grass that never ends, and homes are round tents!",
    tease: "My name starts with, Mon... Mon...",
    capTease: "My capital city starts with, Ulaan... Ulaan...",
    flagHint: "Red and blue with golden signs on the side!" },
  tw: { hint: "Bubble tea was invented in me! Slurp slurp, boba!",
    tease: "My name starts with, Tai... Tai...",
    capTease: "My capital city starts with, Tai-pe... Tai-pe...",
    flagHint: "Red with a blue corner and a white sun!" },
  mm: { hint: "My pagodas are covered in real gold — twinkle twinkle everywhere!",
    tease: "My name starts with, Myan... Myan...",
    capTease: "My capital city starts with, Nay... Nay...",
    flagHint: "Yellow, green and red with a big white star!" },
  th: { hint: "My elephants say hello with their trunks, and my noodles are world famous!",
    tease: "My name starts with, Thai... Thai...",
    capTease: "My capital city starts with, Bang... Bang...",
    flagHint: "Red, white and blue sleeping stripes — blue in the middle!" },
  la: { hint: "Sticky rice in little baskets, and slow boats on my big river!",
    tease: "My name starts with, Laa... Laa...",
    capTease: "My capital city starts with, Vien... Vien...",
    flagHint: "Red and blue with a white circle like the moon!" },
  kh: { hint: "The biggest temple in the whole world hides in my jungle!",
    tease: "My name starts with, Cam... Cam...",
    capTease: "My capital city starts with, Phnom... Phnom...",
    flagHint: "Red and blue with a white temple in the middle!" },
  vn: { hint: "My noodle soup goes slurp, and boats sail between my stone mountains!",
    tease: "My name starts with, Viet... Viet...",
    capTease: "My capital city starts with, Ha... Ha...",
    flagHint: "Red with one big yellow star!" },
  my: { hint: "Two tall silver towers hold hands with a bridge in me!",
    tease: "My name starts with, Malay... Malay...",
    capTease: "My capital city starts with, Kuala... Kuala...",
    flagHint: "Red and white stripes with a moon and sun-star on blue!" },
  sg: { hint: "My lion has a fish tail and spits water! Whoosh!",
    tease: "My name starts with, Singa... Singa...",
    capTease: "My capital city sounds just like me! Singa... Singa...",
    flagHint: "Red and white with a moon and five little stars!" },
  id: { hint: "I have seventeen thousand islands, and real dragons live on one!",
    tease: "My name starts with, Indo... Indo...",
    capTease: "My capital city starts with, Jakar... Jakar...",
    flagHint: "Red on top, white below — just two stripes!" },
  ph: { hint: "Thousands of islands, the sweetest mangoes, and beep beep jeepneys!",
    tease: "My name starts with, Phili... Phili...",
    capTease: "My capital city starts with, Mani... Mani...",
    flagHint: "Blue and red with a white triangle, sun and stars!" },
  bn: { hint: "I am tiny, but my king lives in the biggest palace in the world!",
    tease: "My name starts with, Bru... Bru...",
    capTease: "My capital city starts with, Bandar... Bandar...",
    flagHint: "Yellow with black and white stripes and a red sign!" },
  kz: { hint: "The very first apples grew in me! And I am so so big!",
    tease: "My name starts with, Kazak... Kazak...",
    capTease: "My capital city starts with, Asta... Asta...",
    flagHint: "Sky blue with a golden sun and a flying eagle!" },
  uz: { hint: "Blue tiled palaces stand on my old Silk Road, and my melons are the sweetest!",
    tease: "My name starts with, Uzbek... Uzbek...",
    capTease: "My capital city starts with, Tash... Tash...",
    flagHint: "Blue, white and green stripes with a moon and stars!" },
  tm: { hint: "My desert has a fire pit that has burned for fifty years — never stops!",
    tease: "My name starts with, Turkmen... Turkmen...",
    capTease: "My capital city starts with, Ashga... Ashga...",
    flagHint: "Green with a beautiful carpet pattern on the side!" },
  kg: { hint: "My golden eagles fly with their hunter friends over big mountains!",
    tease: "My name starts with, Kirgi... Kirgi...",
    capTease: "My capital city starts with, Bish... Bish...",
    flagHint: "Red with a golden sun that has a tent top inside!" },
  tj: { hint: "My mountains are called the Roof of the World — SO high!",
    tease: "My name starts with, Tajik... Tajik...",
    capTease: "My capital city starts with, Dushan... Dushan...",
    flagHint: "Red, white and green with a crown and stars!" },
  af: { hint: "Sweet melons and juicy anaar grow between my big dry mountains!",
    tease: "My name starts with, Afghan... Afghan...",
    capTease: "My capital city starts with, Kaa... Kaa...",
    flagHint: "Black, red and green standing stripes!" },
  sa: { hint: "My desert is giant and sandy, camels walk slowly, and my dates are so sweet!",
    tease: "My name starts with, Saudi... Saudi...",
    capTease: "My capital city starts with, Ree... Ree...",
    flagHint: "Green with white writing and a sword!" },
  ae: { hint: "The tallest building in the WHOLE world stands in me — up up up!",
    tease: "My name starts with, Emi... Emi...",
    capTease: "My capital city starts with, Abu... Abu...",
    flagHint: "Red, green, white and black blocks!" },
  qa: { hint: "The football World Cup came to my desert! Goal!",
    tease: "My name starts with, Kata... Kata...",
    capTease: "My capital city starts with, Doh... Doh...",
    flagHint: "Dark red and white with a zigzag line!" },
  om: { hint: "I smell of magic frankincense, and dolphins jump in my sea!",
    tease: "My name starts with, Oh... Oh...",
    capTease: "My capital city starts with, Mus... Mus...",
    flagHint: "Red, white and green with a sword sign in the corner!" },
  ye: { hint: "My old houses look like gingerbread cakes with white icing!",
    tease: "My name starts with, Yeh... Yeh...",
    capTease: "My capital city starts with, Sa... Sa...",
    flagHint: "Red, white and black sleeping stripes!" },
  kw: { hint: "My towers hold big blue balls by the sea!",
    tease: "My name starts with, Kuwai... Kuwai...",
    capTease: "My capital city sounds just like me! Kuwai... Kuwai...",
    flagHint: "Green, white and red with a black shape on the side!" },
  ir: { hint: "Fluffy Persian cats say meow in me, and my carpets look like flower gardens!",
    tease: "My name starts with, Ira... Ira...",
    capTease: "My capital city starts with, Teh... Teh...",
    flagHint: "Green, white and red with a red sign in the middle!" },
  iq: { hint: "The very first writing in the world was invented in me — on clay!",
    tease: "My name starts with, Ira... Iraq...",
    capTease: "My capital city starts with, Bagh... Bagh...",
    flagHint: "Red, white and black with green writing!" },
  tr: { hint: "My name sounds like a bird — gobble gobble! Balloons float over my fairy chimneys!",
    tease: "My name starts with, Tur... Tur...",
    capTease: "My capital city starts with, Anka... Anka...",
    flagHint: "Red with a white moon and star!" },
  sy: { hint: "One of the oldest oldest cities in the world lives in me!",
    tease: "My name starts with, See... See...",
    capTease: "My capital city starts with, Damas... Damas...",
    flagHint: "Red, white and black with two green stars!" },
  jo: { hint: "A whole city is carved into my pink rocks! And my sea makes you float!",
    tease: "My name starts with, Jor... Jor...",
    capTease: "My capital city starts with, Am... Am...",
    flagHint: "Black, white and green with a red triangle and star!" },
  il: { hint: "My sea is SO salty that you float on top like a rubber duck!",
    tease: "My name starts with, Isra... Isra...",
    capTease: "My capital city starts with, Jeru... Jeru...",
    flagHint: "White with blue stripes and a blue star!" },
  lb: { hint: "My big old cedar tree is so special, it is right on my flag!",
    tease: "My name starts with, Leba... Leba...",
    capTease: "My capital city starts with, Bei... Bei...",
    flagHint: "Red and white with a green tree in the middle!" },
  ge: { hint: "In me, people dance with swords — hop hop! And mountains touch the sky!",
    tease: "My name starts with, Jor... Georgia!",
    capTease: "My capital city starts with, Tbi... Tbi...",
    flagHint: "White with five red crosses!" },
  am: { hint: "A big snowy mountain watches over me, and my apricots are the sweetest!",
    tease: "My name starts with, Arme... Arme...",
    capTease: "My capital city starts with, Yere... Yere...",
    flagHint: "Red, blue and orange sleeping stripes!" },
  az: { hint: "I am the land of fire! Little fires burn right out of my ground!",
    tease: "My name starts with, Azer... Azer...",
    capTease: "My capital city starts with, Ba... Ba...",
    flagHint: "Blue, red and green with a moon and star!" },
};

export const VISUALS = {
  in: { icons: '🐯🕌🦚', capIcons: '🏛️🇮🇳',
    capCue: "New Delhi! India Gate stands tall, and the big red Lal Qila fort!" },
  pk: { icons: '🏏🏔️', capIcons: '🕌⛰️',
    capCue: "Islamabad! A big white mosque like a giant tent under green hills!" },
  np: { icons: '🏔️🙏', capIcons: '🛕🐒',
    capCue: "Kathmandu! Old temples where monkeys jump around — oo oo aa aa!" },
  bt: { icons: '🐉😊', capIcons: '🏯🐉',
    capCue: "Thimphu! A big fort-palace where the thunder dragon king lives!" },
  bd: { icons: '🐅🌊', capIcons: '🛺🌈',
    capCue: "Dhaka! Ring ring! Colourful rickshaws painted like rainbows everywhere!" },
  lk: { icons: '🐘🥥🏝️', capIcons: '🚂🌊',
    capCue: "Colombo! A train runs right next to the blue blue sea — chhuk chhuk!" },
  cn: { icons: '🐼🧱🎋', capIcons: '🏯🐉',
    capCue: "Beijing! The Forbidden City — a giant palace with shiny golden roofs!" },
  jp: { icons: '🌸🚄🍣', capIcons: '🗼🤖',
    capCue: "Tokyo! A big red-and-white tower, friendly robots, and the busiest crossing in the world!" },
  kr: { icons: '🎤💃🥬', capIcons: '🏯📱',
    capCue: "Seoul! Old palaces stand right next to shiny tall towers!" },
  kp: { icons: '🤫⭐', capIcons: '🗼⭐',
    capCue: "Pyongyang! A big tall tower with a red star on top!" },
  mn: { icons: '🐎⛺🦅', capIcons: '🐎🗿',
    capCue: "Ulaanbaatar! The biggest horse-rider statue in the whole world!" },
  tw: { icons: '🧋🍜', capIcons: '🏙️🎋',
    capCue: "Taipei! A tower so tall it looks like bamboo reaching the sky!" },
  mm: { icons: '🛕✨', capIcons: '🛕🌟',
    capCue: "Naypyidaw! A golden pagoda that sparkles and sparkles at night!" },
  th: { icons: '🐘🍜🥭', capIcons: '🛕🛶',
    capCue: "Bangkok! Golden temples, and boats selling mangoes on the river!" },
  la: { icons: '🍚🛶', capIcons: '🛕🌅',
    capCue: "Vientiane! A golden stupa that glows like a little sun!" },
  kh: { icons: '🛕🌴', capIcons: '👑🌉',
    capCue: "Phnom Penh! A royal palace with pointy golden roofs by the river!" },
  vn: { icons: '🍜⛵', capIcons: '🛵🏮',
    capCue: "Hanoi! A thousand scooters go beep beep past glowing red lanterns!" },
  my: { icons: '🏙️🌉', capIcons: '🏙️✨',
    capCue: "Kuala Lumpur! The twin Petronas Towers sparkle like two silver rockets!" },
  sg: { icons: '🦁⛲', capIcons: '🌳💡',
    capCue: "Singapore City! Super-trees light up like magic at night!" },
  id: { icons: '🏝️🦎🌋', capIcons: '🗼🔥',
    capCue: "Jakarta! A big monument with a golden flame on top!" },
  ph: { icons: '🥭🚌🏖️', capIcons: '🚌🎨',
    capCue: "Manila! Jeepney buses painted in every colour — like party cars!" },
  bn: { icons: '👑🕌', capIcons: '🕌💧',
    capCue: "Bandar Seri Begawan! A golden mosque that floats on the water!" },
  kz: { icons: '🍎🐎', capIcons: '🏙️❄️',
    capCue: "Astana! Shiny space-age buildings standing in the snow!" },
  uz: { icons: '🕌🍈', capIcons: '🚇🕌',
    capCue: "Tashkent! Even the underground train stations look like blue palaces!" },
  tm: { icons: '🔥🏜️', capIcons: '⬜✨',
    capCue: "Ashgabat! A city of white white marble — everything shines!" },
  kg: { icons: '🦅⛰️', capIcons: '⛰️⛺',
    capCue: "Bishkek! Snowy mountains peek over the whole city!" },
  tj: { icons: '🏔️🏠', capIcons: '🚩🏛️',
    capCue: "Dushanbe! A giant flagpole with a giant giant flag — one of the tallest anywhere!" },
  af: { icons: '🍈⛰️', capIcons: '🪁⛰️',
    capCue: "Kabul! Kites dance in the sky — kite-flying champions live here!" },
  sa: { icons: '🐪🏜️🌴', capIcons: '🏙️🏜️',
    capCue: "Riyadh! Shiny towers rise straight out of the desert sand!" },
  ae: { icons: '🏙️🐪✨', capIcons: '🕌⬜',
    capCue: "Abu Dhabi! A huge white mosque like a palace made of clouds!" },
  qa: { icons: '⚽🏜️', capIcons: '🏙️⛵',
    capCue: "Doha! Glass towers watch little wooden boats sail past!" },
  om: { icons: '🧞🐬', capIcons: '🏰⛵',
    capCue: "Muscat! Old forts guard the sea where dolphins jump and play!" },
  ye: { icons: '🏠🍪', capIcons: '🏠🌙',
    capCue: "Sanaa! Tall mud houses like gingerbread cakes with white sugar lines!" },
  kw: { icons: '🗼🔵', capIcons: '🗼💧',
    capCue: "Kuwait City! Three towers holding big shiny blue-green balls!" },
  ir: { icons: '🐱🌷', capIcons: '🗼🏔️',
    capCue: "Tehran! A tall tall tower under big snowy mountains!" },
  iq: { icons: '📜🌴', capIcons: '🕌📚',
    capCue: "Baghdad! The city from Aladdin's stories — a thousand and one nights!" },
  tr: { icons: '🎈🦃', capIcons: '🏛️🐐',
    capCue: "Ankara! Home of fluffy angora goats with the softest softest wool!" },
  sy: { icons: '🏛️🌹', capIcons: '🌹🏺',
    capCue: "Damascus! Sweet-smelling damask roses come from here!" },
  jo: { icons: '🏛️🐫', capIcons: '🏛️⛰️',
    capCue: "Amman! A city on seven hills with a very old open-air theatre!" },
  il: { icons: '🌊🦆', capIcons: '🏛️🕊️',
    capCue: "Jerusalem! A very very old golden city on a hill!" },
  lb: { icons: '🌲🏔️', capIcons: '🌊🕊️',
    capCue: "Beirut! Big pigeon rocks stand right in the blue blue sea!" },
  ge: { icons: '⛰️🍇🗡️', capIcons: '♨️🏰',
    capCue: "Tbilisi! Warm bubbly bath houses, and a castle up on the hill!" },
  am: { icons: '🏔️🍑', capIcons: '🌸🏛️',
    capCue: "Yerevan! The pink city — buildings made of pink pink stone!" },
  az: { icons: '🔥🛢️', capIcons: '🔥🏙️',
    capCue: "Baku! Three giant glass towers that look like dancing flames!" },
};

// Continent-level clips
export const LEVEL_PREFIX = 'level_as_';
export const ALL_DONE_CLIP = 'all_done_asia';
