// Africa content: names, capitals, funny memory cues (Indian English + light Hinglish),
// level grouping, colours, guess-game hints and visual anchors.

export const COUNTRIES = {
  // ---- Level 1: Pyramid North ----
  eg: {
    name: 'Egypt', capital: 'Cairo', color: '#ffca28',
    cue: "Egypt! The great big pyramids — giant stone triangles! And the Sphinx — half lion, half man!",
    findcap: "Cairo! Where does Cairo live? Find Cairo's country!",
  },
  ly: {
    name: 'Libya', capital: 'Tripoli', color: '#66bb6a',
    cue: "Libya! Desert desert everywhere — the biggest sand pit in the world!",
    findcap: "Tripoli! Where does Tripoli live? Find Tripoli's country!",
  },
  tn: {
    name: 'Tunisia', capital: 'Tunis', color: '#4dd0e1',
    cue: "Tunisia! Blue and white houses by the sparkly sea, and sweet sweet dates!",
    findcap: "Tunis! Where does Tunis live? Find Tunis's country!",
  },
  dz: {
    name: 'Algeria', capital: 'Algiers', color: '#ef9a4d',
    cue: "Algeria! The biggest country in ALL of Africa — big big desert!",
    findcap: "Algiers! Where does Algiers live? Find Algiers' country!",
  },
  ma: {
    name: 'Morocco', capital: 'Rabat', color: '#e57373',
    cue: "Morocco! Colourful markets, flying-carpet stories, and sweet mint tea!",
    findcap: "Rabat! Where does Rabat live? Find Rabat's country!",
  },

  // ---- Level 2: Sahara Friends ----
  mr: {
    name: 'Mauritania', capital: 'Nouakchott', color: '#81c784',
    cue: "Mauritania! A train SO long it looks like a metal snake sliding through the desert!",
    findcap: "Nouakchott! Where does Nouakchott live? Find its country!",
  },
  ml: {
    name: 'Mali', capital: 'Bamako', color: '#ba68c8',
    cue: "Mali! A whole big mosque made of mud — and everyone fixes it together every year!",
    findcap: "Bamako! Where does Bamako live? Find Bamako's country!",
  },
  ne: {
    name: 'Niger', capital: 'Niamey', color: '#ffb74d',
    cue: "Niger! Giraffes walk in the desert here — the last desert giraffes in the world!",
    findcap: "Niamey! Where does Niamey live? Find Niamey's country!",
  },
  td: {
    name: 'Chad', capital: "N'Djamena", color: '#4db6ac',
    cue: "Chad! A big big lake that hippos love — splash splash!",
    findcap: "N'Djamena! Where does N'Djamena live? Find its country!",
  },
  sd: {
    name: 'Sudan', capital: 'Khartoum', color: '#f06292',
    cue: "Sudan! Even MORE pyramids than Egypt — so many little pointy pyramids!",
    findcap: "Khartoum! Where does Khartoum live? Find Khartoum's country!",
  },

  // ---- Level 3: West Coast ----
  sn: {
    name: 'Senegal', capital: 'Dakar', color: '#5c9ce6',
    cue: "Senegal! A pink lake! Really truly pink — like strawberry milk!",
    findcap: "Dakar! Where does Dakar live? Find Dakar's country!",
  },
  gm: {
    name: 'Gambia', capital: 'Banjul', color: '#ff8a65',
    cue: "Gambia! The smallest country on mainland Africa — a little river with land hugging it!",
    findcap: "Banjul! Where does Banjul live? Find Banjul's country!",
  },
  gw: {
    name: 'Guinea-Bissau', capital: 'Bissau', color: '#9575cd',
    cue: "Guinea-Bissau! Hippos swim in the salty SEA here — beach hippos!",
    findcap: "Bissau! Where does Bissau live? Find Bissau's country!",
  },
  gn: {
    name: 'Guinea', capital: 'Conakry', color: '#26a69a',
    cue: "Guinea! So much rain that waterfalls appear everywhere — whoosh!",
    findcap: "Conakry! Where does Conakry live? Find Conakry's country!",
  },
  sl: {
    name: 'Sierra Leone', capital: 'Freetown', color: '#d4e157',
    cue: "Sierra Leone! The Lion Mountains — the hills go roarrr!",
    findcap: "Freetown! Where does Freetown live? Find Freetown's country!",
  },
  lr: {
    name: 'Liberia', capital: 'Monrovia', color: '#29b6f6',
    cue: "Liberia! The land of the free, with big waves for surfing!",
    findcap: "Monrovia! Where does Monrovia live? Find Monrovia's country!",
  },

  // ---- Level 4: Chocolate Coast ----
  ci: {
    name: 'Ivory Coast', capital: 'Yamoussoukro', color: '#a1887f',
    cue: "Ivory Coast! Chocolate country number ONE — the most cocoa in the whole world!",
    findcap: "Yamoussoukro! Where does Yamoussoukro live? Find its country!",
  },
  gh: {
    name: 'Ghana', capital: 'Accra', color: '#ffd54f',
    cue: "Ghana! Chocolate and gold, and the friendliest welcome — akwaaba!",
    findcap: "Accra! Where does Accra live? Find Accra's country!",
  },
  tg: {
    name: 'Togo', capital: 'Lomé', color: '#7986cb',
    cue: "Togo! A tiny stripe of a country — long and thin like a ruler!",
    findcap: "Lomé! Where does Lomé live? Find Lomé's country!",
  },
  bj: {
    name: 'Benin', capital: 'Porto-Novo', color: '#ec407a',
    cue: "Benin! Whole villages built on water — houses standing on stilts like long legs!",
    findcap: "Porto-Novo! Where does Porto-Novo live? Find its country!",
  },
  bf: {
    name: 'Burkina Faso', capital: 'Ouagadougou', color: '#66bb6a',
    cue: "Burkina Faso! The land of honest people — with the funnest capital name ever!",
    findcap: "Ouagadougou! Where does Ouagadougou live? Find its country!",
  },
  ng: {
    name: 'Nigeria', capital: 'Abuja', color: '#4fc3f7',
    cue: "Nigeria! The MOST people in Africa — big movies, big music, big everything!",
    findcap: "Abuja! Where does Abuja live? Find Abuja's country!",
  },

  // ---- Level 5: Jungle Middle ----
  cm: {
    name: 'Cameroon', capital: 'Yaoundé', color: '#aed581',
    cue: "Cameroon! The football lions play here — the Indomitable Lions! Roar, goal!",
    findcap: "Yaoundé! Where does Yaoundé live? Find Yaoundé's country!",
  },
  cf: {
    name: 'Central African Republic', capital: 'Bangui', color: '#ce93d8',
    cue: "The Central African Republic! Right in the middle of Africa, where forest elephants hide in the trees!",
    findcap: "Bangui! Where does Bangui live? Find Bangui's country!",
  },
  ss: {
    name: 'South Sudan', capital: 'Juba', color: '#ffee58',
    cue: "South Sudan! The newest country in the whole world — a baby country!",
    findcap: "Juba! Where does Juba live? Find Juba's country!",
  },
  ga: {
    name: 'Gabon', capital: 'Libreville', color: '#4db6ac',
    cue: "Gabon! Gorillas and elephants walk right on the BEACH here!",
    findcap: "Libreville! Where does Libreville live? Find Libreville's country!",
  },
  cg: {
    name: 'Congo', capital: 'Brazzaville', color: '#ff7043',
    cue: "Congo! The fanciest dressers in the world live here — suits of every colour!",
    findcap: "Brazzaville! Where does Brazzaville live? Find its country!",
  },
  cd: {
    name: 'DR Congo', capital: 'Kinshasa', color: '#42a5f5',
    cue: "The big Congo! A river SO deep, rumba music, and bonobos — the kindest monkeys!",
    findcap: "Kinshasa! Where does Kinshasa live? Find Kinshasa's country!",
  },
  gq: {
    name: 'Equatorial Guinea', capital: 'Malabo', color: '#f48fb1',
    cue: "Equatorial Guinea! A country half on land, half on an island!",
    findcap: "Malabo! Where does Malabo live? Find Malabo's country!",
  },

  // ---- Level 6: Safari East ----
  et: {
    name: 'Ethiopia', capital: 'Addis Ababa', color: '#7e57c2',
    cue: "Ethiopia! Where coffee was discovered — by dancing goats! And churches carved into rock!",
    findcap: "Addis Ababa! Where does Addis Ababa live? Find its country!",
  },
  er: {
    name: 'Eritrea', capital: 'Asmara', color: '#26c6da',
    cue: "Eritrea! Camels carry everything, and dolphins play in the sea!",
    findcap: "Asmara! Where does Asmara live? Find Asmara's country!",
  },
  dj: {
    name: 'Djibouti', capital: 'Djibouti City', color: '#9ccc65',
    cue: "Djibouti! A lake SO salty it sparkles white — in the hottest place around!",
    findcap: "Djibouti City! Where does Djibouti City live? Find its country!",
  },
  so: {
    name: 'Somalia', capital: 'Mogadishu', color: '#64b5f6',
    cue: "Somalia! The longest beach in all of Africa — sand for days and days!",
    findcap: "Mogadishu! Where does Mogadishu live? Find its country!",
  },
  ke: {
    name: 'Kenya', capital: 'Nairobi', color: '#ef5350',
    cue: "Kenya! Safari! Lions, giraffes, zebras — and the great wildebeest run, thump thump thump!",
    findcap: "Nairobi! Where does Nairobi live? Find Nairobi's country!",
  },
  ug: {
    name: 'Uganda', capital: 'Kampala', color: '#ffb300',
    cue: "Uganda! Mountain gorillas live here — big gentle giants!",
    findcap: "Kampala! Where does Kampala live? Find Kampala's country!",
  },

  // ---- Level 7: Lakes & Falls ----
  rw: {
    name: 'Rwanda', capital: 'Kigali', color: '#8d6e63',
    cue: "Rwanda! The land of a thousand hills — up down, up down, up down!",
    findcap: "Kigali! Where does Kigali live? Find Kigali's country!",
  },
  bi: {
    name: 'Burundi', capital: 'Gitega', color: '#ab47bc',
    cue: "Burundi! Drummers drum SO loud the whole country dances! Dum dum dum!",
    findcap: "Gitega! Where does Gitega live? Find Gitega's country!",
  },
  tz: {
    name: 'Tanzania', capital: 'Dodoma', color: '#4dd0e1',
    cue: "Tanzania! Kilimanjaro — Africa's tallest mountain wearing a snowy hat! And zebras everywhere!",
    findcap: "Dodoma! Where does Dodoma live? Find Dodoma's country!",
  },
  mw: {
    name: 'Malawi', capital: 'Lilongwe', color: '#ff8a65',
    cue: "Malawi! A lake full of fish of EVERY colour — a rainbow underwater!",
    findcap: "Lilongwe! Where does Lilongwe live? Find Lilongwe's country!",
  },
  zm: {
    name: 'Zambia', capital: 'Lusaka', color: '#81c784',
    cue: "Zambia! Victoria Falls — the smoke that thunders! The biggest water curtain in the world!",
    findcap: "Lusaka! Where does Lusaka live? Find Lusaka's country!",
  },
  mz: {
    name: 'Mozambique', capital: 'Maputo', color: '#fdd835',
    cue: "Mozambique! Long long beaches with little boats with white sails!",
    findcap: "Maputo! Where does Maputo live? Find Maputo's country!",
  },
  zw: {
    name: 'Zimbabwe', capital: 'Harare', color: '#5c9ce6',
    cue: "Zimbabwe! Great stone houses built long long ago — big walls with no glue at all!",
    findcap: "Harare! Where does Harare live? Find Harare's country!",
  },

  // ---- Level 8: The Deep South ----
  ao: {
    name: 'Angola', capital: 'Luanda', color: '#ef9a4d',
    cue: "Angola! Giant sable antelopes with big moon-shaped horns!",
    findcap: "Luanda! Where does Luanda live? Find Luanda's country!",
  },
  na: {
    name: 'Namibia', capital: 'Windhoek', color: '#e57373',
    cue: "Namibia! The oldest desert in the world — with the BIGGEST sand dunes to climb and roll down!",
    findcap: "Windhoek! Where does Windhoek live? Find Windhoek's country!",
  },
  bw: {
    name: 'Botswana', capital: 'Gaborone', color: '#26a69a',
    cue: "Botswana! A magic river that never reaches the sea — it spreads into a watery animal playground!",
    findcap: "Gaborone! Where does Gaborone live? Find Gaborone's country!",
  },
  za: {
    name: 'South Africa', capital: 'Pretoria', color: '#ba68c8',
    cue: "South Africa! Penguins on sunny beaches — real penguins! And a mountain with a flat flat top!",
    findcap: "Pretoria! Where does Pretoria live? Find Pretoria's country!",
  },
  ls: {
    name: 'Lesotho', capital: 'Maseru', color: '#ffca28',
    cue: "Lesotho! A country INSIDE another country — high high up in the mountains!",
    findcap: "Maseru! Where does Maseru live? Find Maseru's country!",
  },
  sz: {
    name: 'Eswatini', capital: 'Mbabane', color: '#29b6f6',
    cue: "Eswatini! A tiny kingdom where everyone dances together at the big reed dance!",
    findcap: "Mbabane! Where does Mbabane live? Find Mbabane's country!",
  },
  mg: {
    name: 'Madagascar', capital: 'Antananarivo', color: '#9ccc65',
    cue: "Madagascar! Like the movie! Lemurs with stripy tails jump around upside-down baobab trees!",
    findcap: "Antananarivo! Where does Antananarivo live? Find its country!",
  },
};

export const LEVELS = [
  { name: 'Pyramid North', emoji: '🐫', ccs: ['eg', 'ly', 'tn', 'dz', 'ma'] },
  { name: 'Sahara Friends', emoji: '🏜️', ccs: ['mr', 'ml', 'ne', 'td', 'sd'] },
  { name: 'West Coast', emoji: '🌊', ccs: ['sn', 'gm', 'gw', 'gn', 'sl', 'lr'] },
  { name: 'Chocolate Coast', emoji: '🍫', ccs: ['ci', 'gh', 'tg', 'bj', 'bf', 'ng'] },
  { name: 'Jungle Middle', emoji: '🦍', ccs: ['cm', 'cf', 'ss', 'ga', 'cg', 'cd', 'gq'] },
  { name: 'Safari East', emoji: '🦁', ccs: ['et', 'er', 'dj', 'so', 'ke', 'ug'] },
  { name: 'Lakes & Falls', emoji: '🥁', ccs: ['rw', 'bi', 'tz', 'mw', 'zm', 'mz', 'zw'] },
  { name: 'The Deep South', emoji: '🐧', ccs: ['ao', 'na', 'bw', 'za', 'ls', 'sz', 'mg'] },
];

/* Short display names so labels fit inside small countries */
export const SHORT = {
  eg: 'Egypt', ly: 'Libya', tn: 'Tunisia', dz: 'Algeria', ma: 'Morocco',
  mr: 'Maurit.', ml: 'Mali', ne: 'Niger', td: 'Chad', sd: 'Sudan',
  sn: 'Senegal', gm: 'Gambia', gw: 'G.Bissau', gn: 'Guinea', sl: 'S.Leone',
  lr: 'Liberia', ci: 'Ivory C.', gh: 'Ghana', tg: 'Togo', bj: 'Benin',
  bf: 'Burkina', ng: 'Nigeria', cm: 'Camer.', cf: 'C.A.R.', ss: 'S.Sudan',
  ga: 'Gabon', cg: 'Congo', cd: 'DR Congo', gq: 'Eq.Guinea', et: 'Ethiopia',
  er: 'Eritrea', dj: 'Djibouti', so: 'Somalia', ke: 'Kenya', ug: 'Uganda',
  rw: 'Rwanda', bi: 'Burundi', tz: 'Tanzania', mw: 'Malawi', zm: 'Zambia',
  mz: 'Mozamb.', zw: 'Zimb.', ao: 'Angola', na: 'Namibia', bw: 'Botsw.',
  za: 'S.Africa', ls: 'Lesotho', sz: 'Eswatini', mg: 'Madag.',
};

export const GUESS = {
  eg: { hint: "My giant stone triangles are famous everywhere — pyramids! And my Sphinx is half lion, half man!",
    tease: "My name starts with, Ee... Ee...",
    capTease: "My capital city starts with, Kai... Kai...",
    flagHint: "Red, white and black with a golden eagle!" },
  ly: { hint: "I am almost ALL desert — the biggest sand pit in the world!",
    tease: "My name starts with, Li... Li...",
    capTease: "My capital city starts with, Tri... Tri...",
    flagHint: "Red, black and green with a white moon and star!" },
  tn: { hint: "My houses are blue and white by the sparkly sea, and my dates are so sweet!",
    tease: "My name starts with, Tyoo... Tyoo...",
    capTease: "My capital city starts with, Too... Too...",
    flagHint: "Red with a white circle, a red moon and star!" },
  dz: { hint: "I am the BIGGEST country in all of Africa!",
    tease: "My name starts with, Al... Al...",
    capTease: "My capital city starts with, Al-jee... Al-jee...",
    flagHint: "Green and white with a red moon and star!" },
  ma: { hint: "Colourful markets, flying-carpet stories, and sweet mint tea live in me!",
    tease: "My name starts with, Mo... Mo...",
    capTease: "My capital city starts with, Ra... Ra...",
    flagHint: "Red with a green star!" },
  mr: { hint: "A train SO long it looks like a metal snake slides through my desert!",
    tease: "My name starts with, Mauri... Mauri...",
    capTease: "My capital city starts with, Nwak... Nwak...",
    flagHint: "Green with a golden moon and star and red stripes!" },
  ml: { hint: "My big mosque is made of mud, and everyone fixes it together every year!",
    tease: "My name starts with, Maa... Maa...",
    capTease: "My capital city starts with, Bama... Bama...",
    flagHint: "Green, yellow and red standing stripes!" },
  ne: { hint: "Giraffes walk in my desert — the last desert giraffes in the world!",
    tease: "My name starts with, Nee... Nee...",
    capTease: "My capital city starts with, Nia... Nia...",
    flagHint: "Orange, white and green with an orange circle!" },
  td: { hint: "My big lake is full of happy hippos — splash splash!",
    tease: "My name starts with, Cha... Cha...",
    capTease: "My capital city starts with, Nja... Nja...",
    flagHint: "Blue, yellow and red standing stripes!" },
  sd: { hint: "I have even MORE pyramids than Egypt — so many little pointy ones!",
    tease: "My name starts with, Soo... Soo...",
    capTease: "My capital city starts with, Khar... Khar...",
    flagHint: "Red, white and black with a green triangle!" },
  sn: { hint: "My lake is PINK! Really truly pink, like strawberry milk!",
    tease: "My name starts with, Sene... Sene...",
    capTease: "My capital city starts with, Da... Da...",
    flagHint: "Green, yellow and red with a green star in the middle!" },
  gm: { hint: "I am the smallest country on mainland Africa — a river with land hugging it!",
    tease: "My name starts with, Gam... Gam...",
    capTease: "My capital city starts with, Ban... Ban...",
    flagHint: "Red, blue and green sleeping stripes with white lines!" },
  gw: { hint: "My hippos swim in the salty SEA — beach hippos!",
    tease: "My name starts with, Guinea Bi... Guinea Bi...",
    capTease: "My capital city starts with, Bi... Bi...",
    flagHint: "A black star on red, with yellow and green!" },
  gn: { hint: "It rains SO much in me that waterfalls appear everywhere!",
    tease: "My name starts with, Gi... Gi...",
    capTease: "My capital city starts with, Cona... Cona...",
    flagHint: "Red, yellow and green standing stripes!" },
  sl: { hint: "My mountains are called the Lion Mountains — they go roarrr!",
    tease: "My name starts with, Sierra... Sierra...",
    capTease: "My capital city starts with, Free... Free...",
    flagHint: "Green, white and blue sleeping stripes!" },
  lr: { hint: "I am the land of the free, with big waves for surfing!",
    tease: "My name starts with, Li-bee... Li-bee...",
    capTease: "My capital city starts with, Mon... Mon...",
    flagHint: "Red and white stripes with one white star on blue!" },
  ci: { hint: "I am chocolate country number ONE — the most cocoa in the whole world!",
    tease: "My name starts with, Ivory... Ivory...",
    capTease: "My capital city starts with, Yamu... Yamu...",
    flagHint: "Orange, white and green standing stripes!" },
  gh: { hint: "Chocolate and gold come from me, and I say the friendliest welcome — akwaaba!",
    tease: "My name starts with, Gaa... Gaa...",
    capTease: "My capital city starts with, Ak... Ak...",
    flagHint: "Red, yellow and green with a black star!" },
  tg: { hint: "I am a tiny stripe of a country — long and thin like a ruler!",
    tease: "My name starts with, Toh... Toh...",
    capTease: "My capital city starts with, Lo... Lo...",
    flagHint: "Green and yellow stripes with a white star on red!" },
  bj: { hint: "My villages are built on water — houses standing on stilts like long legs!",
    tease: "My name starts with, Beh... Beh...",
    capTease: "My capital city starts with, Porto... Porto...",
    flagHint: "Green on the side, with yellow and red!" },
  bf: { hint: "I am the land of honest people, and my capital has the funnest name ever!",
    tease: "My name starts with, Burki... Burki...",
    capTease: "My capital city starts with, Waga... Waga...",
    flagHint: "Red and green with a yellow star!" },
  ng: { hint: "I have the MOST people in Africa — big movies, big music, big everything!",
    tease: "My name starts with, Nai... Nai...",
    capTease: "My capital city starts with, Abu... Abu...",
    flagHint: "Green, white, green standing stripes!" },
  cm: { hint: "My football lions roar and score — the Indomitable Lions!",
    tease: "My name starts with, Came... Came...",
    capTease: "My capital city starts with, Yaun... Yaun...",
    flagHint: "Green, red and yellow with a yellow star!" },
  cf: { hint: "I sit right in the middle of Africa, where forest elephants hide in the trees!",
    tease: "My name starts with, Central Af... Central Af...",
    capTease: "My capital city starts with, Ban... Ban...",
    flagHint: "Four stripes with a red line down the middle and a yellow star!" },
  ss: { hint: "I am the newest country in the whole world — a baby country!",
    tease: "My name starts with, South Soo... South Soo...",
    capTease: "My capital city starts with, Joo... Joo...",
    flagHint: "Black, red and green with a blue triangle and gold star!" },
  ga: { hint: "My gorillas and elephants walk right on the beach!",
    tease: "My name starts with, Gab... Gab...",
    capTease: "My capital city starts with, Libre... Libre...",
    flagHint: "Green, yellow and blue sleeping stripes!" },
  cg: { hint: "The fanciest dressers in the world live in me — suits of every colour!",
    tease: "My name starts with, Con... Con...",
    capTease: "My capital city starts with, Brazza... Brazza...",
    flagHint: "Green, yellow and red — slanted stripes!" },
  cd: { hint: "My river is SO deep, my music makes everyone dance, and my bonobos are the kindest monkeys!",
    tease: "My name starts with, D R Con... D R Con...",
    capTease: "My capital city starts with, Kin... Kin...",
    flagHint: "Sky blue with a yellow star and a red stripe!" },
  gq: { hint: "I am half on land and half on an island!",
    tease: "My name starts with, Equato... Equato...",
    capTease: "My capital city starts with, Mala... Mala...",
    flagHint: "Green, white and red with a blue triangle!" },
  et: { hint: "Coffee was discovered in me — by dancing goats! And my churches are carved into rock!",
    tease: "My name starts with, Ethi... Ethi...",
    capTease: "My capital city starts with, Addis... Addis...",
    flagHint: "Green, yellow and red with a blue circle and star!" },
  er: { hint: "My camels carry everything, and dolphins play in my sea!",
    tease: "My name starts with, Eri... Eri...",
    capTease: "My capital city starts with, As... As...",
    flagHint: "A red triangle with a golden branch, green and blue!" },
  dj: { hint: "My lake is SO salty it sparkles white — and I am the hottest place around!",
    tease: "My name starts with, Jib... Jib...",
    capTease: "My capital city sounds just like me! Jib... Jib...",
    flagHint: "Blue and green with a white triangle and red star!" },
  so: { hint: "I have the longest beach in all of Africa — sand for days and days!",
    tease: "My name starts with, Soma... Soma...",
    capTease: "My capital city starts with, Moga... Moga...",
    flagHint: "Sky blue with one big white star!" },
  ke: { hint: "Safari! My lions, giraffes and zebras run the great big run — thump thump thump!",
    tease: "My name starts with, Ken... Ken...",
    capTease: "My capital city starts with, Nai... Nai...",
    flagHint: "Black, red and green with a warrior shield!" },
  ug: { hint: "Mountain gorillas live in me — big gentle giants!",
    tease: "My name starts with, Yoo-gan... Yoo-gan...",
    capTease: "My capital city starts with, Kam... Kam...",
    flagHint: "Black, yellow and red stripes with a pretty bird!" },
  rw: { hint: "I am the land of a thousand hills — up down, up down!",
    tease: "My name starts with, Rwa... Rwa...",
    capTease: "My capital city starts with, Ki... Ki...",
    flagHint: "Blue, yellow and green with a little sun!" },
  bi: { hint: "My drummers drum SO loud the whole country dances!",
    tease: "My name starts with, Burun... Burun...",
    capTease: "My capital city starts with, Gi... Gi...",
    flagHint: "Red and green with a white cross and three stars!" },
  tz: { hint: "Africa's tallest mountain wears a snowy hat in me — and zebras run everywhere!",
    tease: "My name starts with, Tanza... Tanza...",
    capTease: "My capital city starts with, Do... Do...",
    flagHint: "Green and blue with a black stripe corner to corner!" },
  mw: { hint: "My lake is full of fish of EVERY colour — a rainbow underwater!",
    tease: "My name starts with, Mala... Mala...",
    capTease: "My capital city starts with, Lilong... Lilong...",
    flagHint: "Black, red and green with a rising sun!" },
  zm: { hint: "My waterfall is called the smoke that thunders — the biggest water curtain in the world!",
    tease: "My name starts with, Zam... Zam...",
    capTease: "My capital city starts with, Lusa... Lusa...",
    flagHint: "Green with an orange eagle and stripes in the corner!" },
  mz: { hint: "My beaches are long long, with little boats with white sails!",
    tease: "My name starts with, Mozam... Mozam...",
    capTease: "My capital city starts with, Mapu... Mapu...",
    flagHint: "Green, black and yellow with a red triangle and star!" },
  zw: { hint: "My great stone houses were built long long ago — big walls with no glue!",
    tease: "My name starts with, Zimba... Zimba...",
    capTease: "My capital city starts with, Hara... Hara...",
    flagHint: "Green, yellow, red and black stripes with a bird and star!" },
  ao: { hint: "My giant antelopes have big moon-shaped horns!",
    tease: "My name starts with, Ango... Ango...",
    capTease: "My capital city starts with, Luan... Luan...",
    flagHint: "Red and black with a yellow sign in the middle!" },
  na: { hint: "My desert is the oldest in the world, with the BIGGEST sand dunes to roll down!",
    tease: "My name starts with, Nami... Nami...",
    capTease: "My capital city starts with, Wind... Wind...",
    flagHint: "A blue triangle with a sun, a red stripe, and green!" },
  bw: { hint: "My magic river never reaches the sea — it spreads into a watery animal playground!",
    tease: "My name starts with, Botswa... Botswa...",
    capTease: "My capital city starts with, Gabo... Gabo...",
    flagHint: "Sky blue with a black and white zebra stripe!" },
  za: { hint: "Penguins waddle on my sunny beaches, and my mountain has a flat flat top!",
    tease: "My name starts with, South Af... South Af...",
    capTease: "My capital city starts with, Pre... Pre...",
    flagHint: "Six colours with a big sideways Y!" },
  ls: { hint: "I am a country INSIDE another country — high up in the mountains!",
    tease: "My name starts with, Leso... Leso...",
    capTease: "My capital city starts with, Mase... Mase...",
    flagHint: "Blue, white and green with a black hat in the middle!" },
  sz: { hint: "I am a tiny kingdom where everyone dances together at the big reed dance!",
    tease: "My name starts with, Eswa... Eswa...",
    capTease: "My capital city starts with, Mba... Mba...",
    flagHint: "Blue and red with a black and white shield!" },
  mg: { hint: "Lemurs with stripy tails jump around my upside-down baobab trees — like in the movie!",
    tease: "My name starts with, Mada... Mada...",
    capTease: "My capital city starts with, Antana... Antana...",
    flagHint: "White, red and green blocks!" },
};

export const VISUALS = {
  eg: { icons: '🔺🐫🦁', capIcons: '🔺🌊',
    capCue: "Cairo! The pyramids stand right at the edge of the city, and the long long Nile river flows through!" },
  ly: { icons: '🏜️☀️', capIcons: '🏛️🌊',
    capCue: "Tripoli! White buildings shining by the blue blue sea!" },
  tn: { icons: '🚪🔵', capIcons: '🚪✨',
    capCue: "Tunis! Doors painted blue with pretty star patterns everywhere!" },
  dz: { icons: '🏜️🐪', capIcons: '⬜🌊',
    capCue: "Algiers! A white white city climbing up the hill from the sea!" },
  ma: { icons: '🧞🍵', capIcons: '🗼🐦',
    capCue: "Rabat! An old old tower where storks build big messy nests on top!" },
  mr: { icons: '🚂🏜️', capIcons: '🎣🌈',
    capCue: "Nouakchott! Fishing boats painted every colour land on the big beach!" },
  ml: { icons: '🕌🧱', capIcons: '🥁🛶',
    capCue: "Bamako! Boats float on the big river and drums go dum dum dum!" },
  ne: { icons: '🦒🏜️', capIcons: '🐪🛶',
    capCue: "Niamey! Camels and canoes meet at the big bending river!" },
  td: { icons: '🦛💦', capIcons: '🌊🤗',
    capCue: "N'Djamena! A city where two rivers meet and hug each other!" },
  sd: { icons: '🔺🔺', capIcons: '🌊🌊',
    capCue: "Khartoum! Two Nile rivers — one blue, one white — meet and become one big river!" },
  sn: { icons: '🩷🌊', capIcons: '🗽🌊',
    capCue: "Dakar! A giant statue taller than the buildings looks out over the sea!" },
  gm: { icons: '🌊🤏', capIcons: '🏝️⛵',
    capCue: "Banjul! An island city right where the river says hello to the sea!" },
  gw: { icons: '🦛🏖️', capIcons: '🎭🎉',
    capCue: "Bissau! Carnival time — everyone wears big colourful animal masks!" },
  gn: { icons: '💦⛰️', capIcons: '🥭🏝️',
    capCue: "Conakry! A city stretching into the sea, with mango trees everywhere!" },
  sl: { icons: '🦁⛰️', capIcons: '🌳🏠',
    capCue: "Freetown! A giant old cotton tree stands right in the middle of the city!" },
  lr: { icons: '🏄🌊', capIcons: '🌧️☔',
    capCue: "Monrovia! The rainiest capital in the world — don't forget your umbrella!" },
  ci: { icons: '🍫🌳', capIcons: '⛪🐊',
    capCue: "Yamoussoukro! One of the biggest churches in the world — and crocodiles in the lake nearby!" },
  gh: { icons: '🍫✨', capIcons: '🧵🌈',
    capCue: "Accra! Kente cloth with stripes of every colour — so so pretty!" },
  tg: { icons: '📏🌴', capIcons: '🧺🛍️',
    capCue: "Lomé! A big big market where grandmothers sell beautiful cloth!" },
  bj: { icons: '🏠🌊', capIcons: '👑🏛️',
    capCue: "Porto-Novo! Old palaces full of kings' stories and paintings!" },
  bf: { icons: '😄🤝', capIcons: '😄🎉',
    capCue: "Ouagadougou! Say it with me — Waga-doo-goo! The funnest name to say!" },
  ng: { icons: '🎬🥁', capIcons: '🪨🏙️',
    capCue: "Abuja! A giant round rock stands guard over the whole city!" },
  cm: { icons: '⚽🦁', capIcons: '⛰️🌿',
    capCue: "Yaoundé! A city built on seven green hills!" },
  cf: { icons: '🐘🌳', capIcons: '🛶🌊',
    capCue: "Bangui! The river is the road here — boats go everywhere!" },
  ss: { icons: '👶🆕', capIcons: '🌊🏗️',
    capCue: "Juba! A brand new city growing on the great White Nile!" },
  ga: { icons: '🦍🏖️', capIcons: '🐒🌴',
    capCue: "Libreville! The rainforest is right next door — monkeys are neighbours!" },
  cg: { icons: '👔🌈', capIcons: '👋🌊',
    capCue: "Brazzaville! From here you can SEE another capital across the river — hello neighbour!" },
  cd: { icons: '🐒🎶', capIcons: '🎶💃',
    capCue: "Kinshasa! The music city — everyone sings and dances the rumba!" },
  gq: { icons: '🏝️🌋', capIcons: '🌋🏝️',
    capCue: "Malabo! A capital on an island, sitting under a big volcano!" },
  et: { icons: '☕🐐', capIcons: '🌸⛰️',
    capCue: "Addis Ababa! The name means New Flower — a city high high in the mountains!" },
  er: { icons: '🐪🐬', capIcons: '🏛️🎨',
    capCue: "Asmara! A city full of pretty old buildings like toy houses!" },
  dj: { icons: '🧂☀️', capIcons: '🦈💙',
    capCue: "Djibouti City! Whale sharks — the biggest, gentlest fish — swim right offshore!" },
  so: { icons: '🏖️🐪', capIcons: '⬜🌊',
    capCue: "Mogadishu! White houses by the bluest blue sea!" },
  ke: { icons: '🦁🦒🦓', capIcons: '🦒🏙️',
    capCue: "Nairobi! The only city with a safari park inside it — giraffes near the buildings!" },
  ug: { icons: '🦍💚', capIcons: '⛰️🌊',
    capCue: "Kampala! A city on hills beside the biggest lake in Africa!" },
  rw: { icons: '⛰️🦍', capIcons: '✨🧹',
    capCue: "Kigali! The cleanest city in Africa — everybody helps clean it together!" },
  bi: { icons: '🥁🥁', capIcons: '🥁👑',
    capCue: "Gitega! Home of the big royal drums — boom boom boom!" },
  tz: { icons: '🏔️🦓', capIcons: '🍇🏛️',
    capCue: "Dodoma! Right in the middle of the country, where sweet grapes grow!" },
  mw: { icons: '🐠🌈', capIcons: '❤️🌍',
    capCue: "Lilongwe! The warm heart of Africa beats right here!" },
  zm: { icons: '💦🌈', capIcons: '🌳🏙️',
    capCue: "Lusaka! A city growing tall and wide like a baobab tree!" },
  mz: { icons: '⛵🏖️', capIcons: '🚂✨',
    capCue: "Maputo! A train station SO pretty, people visit just to look at it!" },
  zw: { icons: '🪨🏰', capIcons: '💜🌳',
    capCue: "Harare! Jacaranda trees paint the streets purple purple!" },
  ao: { icons: '🦌🌙', capIcons: '🌊😊',
    capCue: "Luanda! A city curving around the bay like a big smile!" },
  na: { icons: '🏜️🎢', capIcons: '🏰🏜️',
    capCue: "Windhoek! A little castle city in the desert hills!" },
  bw: { icons: '🐘💦', capIcons: '🦓🏙️',
    capCue: "Gaborone! A calm friendly city — with zebras on the money!" },
  za: { icons: '🐧⛰️', capIcons: '💜🌸',
    capCue: "Pretoria! Purple jacaranda flowers cover the whole city in spring!" },
  ls: { icons: '⛰️🎁', capIcons: '🐎🧣',
    capCue: "Maseru! People ride horses wearing warm cosy blankets!" },
  sz: { icons: '💃👑', capIcons: '⛰️💚',
    capCue: "Mbabane! A little capital tucked between green green mountains!" },
  mg: { icons: '🐒🌳', capIcons: '🍚⛰️',
    capCue: "Antananarivo! Say it — Anta-nana-rivo! A city of hills and rice fields!" },
};

// Continent-level clips
export const LEVEL_PREFIX = 'level_af_';
export const ALL_DONE_CLIP = 'all_done_africa';
